### ISSUE TITLE
Apply ELLA node error，TypeError: cannot create weak reference to 'NoneType' object

### ISSUE THREAD

**Issue by whmc76** [TencentQQGYLab/ComfyUI-ELLA#36]
!!! Exception during processing!!! cannot create weak reference to 'NoneType' object
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\custom_nodes\ComfyUI-ELLA\ella.py", line 155, in apply
    model_clone = model.clone()
                  ^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\ComfyUI\comfy\model_patcher.py", line 79, in clone
    n.model_options = copy.deepcopy(self.model_options)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 297, in _reconstruct
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 297, in _reconstruct
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 271, in _reconstruct
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 231, in _deepcopy_dict
  File "copy.py", line 146, in deepcopy
  File "copy.py", line 206, in _deepcopy_list
  File "copy.py", line 172, in deepcopy
  File "copy.py", line 273, in _reconstruct
  File "E:\IMAGE\ComfyUI-base-py311\python_embeded\Lib\site-packages\torch\utils\hooks.py", line 62, in __setstate__
    self.extra_dict_ref = tuple(weakref.ref(d) for d in state[2])
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\IMAGE\ComfyUI-base-py311\python_embeded\Lib\site-packages\torch\utils\hooks.py", line 62, in <genexpr>
    self.extra_dict_ref = tuple(weakref.ref(d) for d in state[2])
                                ^^^^^^^^^^^^^^
TypeError: cannot create weak reference to 'NoneType' object

**Comment by JettHu** [comment]
Do you mind share your workflow

**Comment by whmc76** [comment]
after reboot it worked 迷惑



---Original---
From: ***@***.***&gt;
Date: Wed, May 1, 2024 16:52 PM
To: ***@***.***&gt;;
Cc: "Cyber Dick ***@***.******@***.***&gt;;
Subject: Re: [TencentQQGYLab/ComfyUI-ELLA] Apply ELLA node error，TypeError: cannot create weak reference to 'NoneType' object (Issue #36)




 
Do you mind share your workflow
