### ISSUE TITLE
Can't set attribute "device"

### ISSUE THREAD

**Issue by atxoxx** [TencentQQGYLab/ComfyUI-ELLA#56]
Hello since today I have this error : 

Traceback (most recent call last):
  File "E:\IA\Stability matrix\Data\Packages\Comfy\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\IA\Stability matrix\Data\Packages\Comfy\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\IA\Stability matrix\Data\Packages\Comfy\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\IA\Stability matrix\Data\Packages\Comfy\custom_nodes\ComfyUI-ELLA\ella.py", line 281, in encode
    cond = text_encoder_model(text, max_length=None)
  File "E:\IA\Stability matrix\Data\Packages\Comfy\custom_nodes\ComfyUI-ELLA\model.py", line 136, in __call__
    self.load_model()
  File "E:\IA\Stability matrix\Data\Packages\Comfy\custom_nodes\ComfyUI-ELLA\model.py", line 132, in load_model
    model_management.load_model_gpu(self.patcher)
  File "E:\IA\Stability matrix\Data\Packages\Comfy\comfy\model_management.py", line 474, in load_model_gpu
    return load_models_gpu([model])
  File "E:\IA\Stability matrix\Data\Packages\Comfy\comfy\model_management.py", line 468, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "E:\IA\Stability matrix\Data\Packages\Comfy\comfy\model_management.py", line 296, in model_load
    self.model.unpatch_model(self.model.offload_device)
  File "E:\IA\Stability matrix\Data\Packages\Comfy\comfy\model_patcher.py", line 556, in unpatch_model
    self.model.device = device_to
  File "E:\IA\Stability matrix\Data\Packages\Comfy\venv\lib\site-packages\torch\nn\modules\module.py", line 1754, in __setattr__
    super().__setattr__(name, value)
AttributeError: can't set attribute 'device'

Any idea what's happening ?

**Comment by ka1tte** [comment]
@atxoxx  Have you fixed it?

**Comment by atxoxx** [comment]
> @atxoxx Have you fixed it?

no... 
seems like it is caused by comfyui change 

here is fix by animate diff evolved dev
Gonna take a look on ELLA see if I can do something

**Comment by ka1tte** [comment]
Yes, I have temporarily rolled back to de17a9755ecb8419cb167fe8504791df5b07246f

**Comment by DaveScream** [comment]
property 'device' of 'T5EncoderModel' object has no setter




!!! Exception during processing!!! property 'device' of 'T5EncoderModel' object has no setter
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 294, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to, patch_weights=load_weights)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 306, in patch_model
    self.model.device = device_to
    ^^^^^^^^^^^^^^^^^
  File "D:\SD\venv3.11\Lib\site-packages\torch\nn\modules\module.py", line 1768, in __setattr__
    super().__setattr__(name, value)
AttributeError: property 'device' of 'T5EncoderModel' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ELLA\ella.py", line 281, in encode
    cond = text_encoder_model(text, max_length=None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ELLA\model.py", line 136, in __call__
    self.load_model()
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ELLA\model.py", line 132, in load_model
    model_management.load_model_gpu(self.patcher)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 474, in load_model_gpu
    return load_models_gpu([model])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 468, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 296, in model_load
    self.model.unpatch_model(self.model.offload_device)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 556, in unpatch_model
    self.model.device = device_to
    ^^^^^^^^^^^^^^^^^
  File "D:\SD\venv3.11\Lib\site-packages\torch\nn\modules\module.py", line 1768, in __setattr__
    super().__setattr__(name, value)
AttributeError: property 'device' of 'T5EncoderModel' object has no setter

**Comment by Skuuurt** [comment]
Any fix guys ? this broke my big ass workflow, it would be a shame to start all over again...

**Comment by GammaSix** [comment]
> > @atxoxx Have you fixed it?
> 
> no... seems like it is caused by comfyui change
> 
> here is fix by animate diff evolved dev : [Kosinkadink/ComfyUI-AnimateDiff-Evolved@c1c3bbc](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/commit/c1c3bbc5839bff689cf31aa0af5fe5885b8004a8) Gonna take a look on ELLA see if I can do something
> 
> Edit : this is the comfyui commit that cause the issue : [comfyanonymous/ComfyUI@b334605](https://github.com/comfyanonymous/ComfyUI/commit/b334605a6631c12bbe7b3aff6d77526f47acdf42)

This is a really roundabout fix and I don't know if it's best practice, but I managed to get it working again by downloading the second most recent version for each file listed in that comfyui commit. They were model_base.py, model_management.py, model_patcher.py, and sd.py. Now I just... don't click the "Update" button in SM until this issue is marked as resolved, I guess. I'm still new at this.

**Comment by saphtea** [comment]
also running into this issue!

**Comment by LoathingScreen** [comment]
tried rolling back with no luck, ella workflows are broken

**Comment by atxoxx** [comment]
> > @atxoxx Have you fixed it?
> 
> no... seems like it is caused by comfyui change
> 
> here is fix by animate diff evolved dev : [Kosinkadink/ComfyUI-AnimateDiff-Evolved@c1c3bbc](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved/commit/c1c3bbc5839bff689cf31aa0af5fe5885b8004a8) Gonna take a look on ELLA see if I can do something
> 
> Edit : this is the comfyui commit that cause the issue : [comfyanonymous/ComfyUI@b334605](https://github.com/comfyanonymous/ComfyUI/commit/b334605a6631c12bbe7b3aff6d77526f47acdf42)



> tried rolling back with no luck, ella workflows are broken

you need to rolback comfy before this commit or change the files needed

**Comment by dchatel** [comment]
This is caused by a bug in comfyui.
The actual fix is to remove or comment line 353 in comfy/model_patcher.py:
![image](https://github.com/user-attachments/assets/cff311a5-a437-4797-8ba1-ab09db2ae1e1)
For the explanation:
- line 353 is useless because it is incorrectly trying to achieve what line 352 has already correctly done.
- line 353 will cause bugs to every model whose device property is read only (for example T5Tokenizer).

**Comment by niko2020** [comment]
same isssue here, maybe this can be fixed in ComfyUI-ELLA?

**Comment by JettHu** [comment]
I'll try to fix this problem when I have time, in the next two days.

**Comment by ba161** [comment]
temporary fix
 go to ComfyUI\comfy\model_patcher.py

 search for "self.model.device = device_to"
should be inside "patch_model" function , 
remove or comment it out 

def patch_model(...)
            ....
            if device_to is not None:
                self.model.to(device_to)
                #--------->self.model.device = device_to<-----------------
                self.model.model_loaded_weight_memory = self.model_size()

        return self.model
        
then save and reboot comfy

**Comment by GammaSix** [comment]
This does work for initial ELLA generations, so thank you. However, the workflow does break shortly afterwards when I use VAE Encode to upscale the image. I'll include the error text below, not sure if it's helpful at all.
'''
 Error occurred when executing VAEEncode: 

can't set attribute 'device' 

File "...ComfyUI\execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) 
File "...ComfyUI\execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) 
File "...ComfyUI\execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) File "...ComfyUI\nodes.py", line 310, in encode t = vae.encode(pixels[:,:,:,:3]) 
File "...ComfyUI\comfy\sd.py", line 343, in encode model_management.load_models_gpu([self.patcher], memory_required=memory_used) 
File "...ComfyUI\comfy\model_management.py", line 479, in load_models_gpu free_memory(extra_mem + offloaded_memory(models_already_loaded, d), d, models_already_loaded) 
File "...ComfyUI\comfy\model_management.py", line 423, in free_memory if current_loaded_models[i].model_unload(memory_to_free): 
File "...ComfyUI\comfy\model_management.py", line 344, in model_unload self.model.unpatch_model(self.model.offload_device, unpatch_weights=unpatch_weights) 
File "...ComfyUI\comfy\model_patcher.py", line 619, in unpatch_model self.model.device = device_to 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1754, in __setattr__ super().__setattr__(name, value)'''

THEN, after that error occurs, future generations using ELLA T5 Text Encode all fail:'''
Error occurred when executing T5TextEncode #ELLA: 

"addmm_impl_cpu_" not implemented for 'Half' 

File "...ComfyUI\execution.py", line 152, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) 
File "...ComfyUI\execution.py", line 82, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) 
File "...ComfyUI\execution.py", line 75, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) 
File "...ComfyUI\custom_nodes\ComfyUI-ELLA\ella.py", line 228, in encode cond = text_encoder_model(text, max_length=max_length) 
File "...ComfyUI\custom_nodes\ComfyUI-ELLA\model.py", line 158, in __call__ outputs = self.model(text_input_ids, attention_mask=attention_mask) # type: ignore 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\transformers\models\t5\modeling_t5.py", line 1971, in forward encoder_outputs = self.encoder( 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\transformers\models\t5\modeling_t5.py", line 1106, in forward layer_outputs = layer_module( 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\transformers\models\t5\modeling_t5.py", line 686, in forward self_attention_outputs = self.layer[0]( 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\transformers\models\t5\modeling_t5.py", line 593, in forward attention_output = self.SelfAttention( 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\transformers\models\t5\modeling_t5.py", line 512, in forward query_states = shape(self.q(hidden_states)) # (batch_size, n_heads, seq_length, dim_per_head) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) 
File "...ComfyUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward return F.linear(input, self.weight, self.bias)
'''
Sorry I have no idea if the formatting is right here. For some reason I can only view your reply in email
    On Thursday, August 15, 2024 at 10:37:10 AM EDT, zehumblest ***@***.***> wrote:  
 
 


temporary fix
go to ComfyUI\comfy\model_patcher.py

search for "self.model.device = device_to"
should be inside "patch_model" function ,
remove or comment it out

def patch_model(...)
....
if device_to is not None:
self.model.to(device_to)
#--------->self.model.device = device_to<-----------------
self.model.model_loaded_weight_memory = self.model_size()
    return self.model

then save and reboot comfy

**Comment by JettHu** [comment]
> I'll try to fix this problem when I have time, in the next two days.

fixed

**Comment by atxoxx** [comment]
> > I'll try to fix this problem when I have time, in the next two days.
> 
> fixed

thanks a lot ! 
you're a legend
